steps:
# Build your app using Cloud Build and Buildpacks.io 
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build', '--builder=gcr.io/buildpacks/builder', 
  '--publish', 'us-central1-docker.pkg.dev/hamzalabs/petclinic-artifact-repo/petclinic:latest']

# Deploy your app using Cloud Build to Google Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'petclinic', 
  '--image', 'us-central1-docker.pkg.dev/hamzalabs/petclinic-artifact-repo/petclinic:latest',
  '--region', 'us-central1', '--allow-unauthenticated', '--cpu=2', '--memory=512M',
  '--service-account', 'petclinic@hamzalabs.iam.gserviceaccount.com', 
  '--update-secrets= petclinic-db-instance-connection-name=petclinic-db-instance-connection-name:latest',
  '--update-secrets= petclinic-db-name=petclinic-db-name:latest',
  '--update-secrets= petclinic-db-username=petclinic-db-username:latest',
  '--update-secrets= petclinic-db-password=petclinic-db-password:latest']

options:
  pool:
    name: 'projects/hamzalabs/locations/us-central1/workerPools/cloudbuild-privatepool' 